# Base configs
baseurl: "https://UTRcrew.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: 

# UI configs
title: "Photography by UTRcrew"
subtitle: "See the world through my eyes!"
author: "Sangwon Choi"
header:
 title: "Photography"
 subtitle: "by Sangwon Choi"
footer:
 name: "Hey there, my name is Won"
 bio: "I am a developer work in Seoul. My one of hobby is Photograph"
 github: "If you want to make this website then please contact me"
web_design: "AJ"
social_urls:
  facebook: 
  twitter: 
  instagram: 
  dribbble: 
  linkedin: 
  github: "https://www.github.com/UTRcrew"
